name: everything
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
  lint:
    needs: setup
    steps:
      - run: npm run lint
  build:
    needs: lint
    steps:
      - run: npm run build:server
  test:
    needs: build
    steps:
      - run: npm test
